package com.las.WebData.entity;
// Generated 2017-9-29 16:46:02 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Acmproduct generated by hbm2java
 */
@Entity
@Table(name = "ACMProduct", catalog = "WebData")
public class Acmproduct implements java.io.Serializable {

	private Integer id;
	private String acmproductType;
	private String acmedition;
	private String acmproductIntroduction;
	private String acmproductName;
	private String acmproductrUrl;
	private String acmissn;
	private String acmeissn;
	private String acmproductPicUrl;
	private byte[] acmproductPic;
	private String acmproductPicName;
	private String acmproductDescription;
	private Date createtime;
	private Date updatetime;
	private Set<AcmproductsEditor> acmproductsEditors = new HashSet<AcmproductsEditor>(0);

	public Acmproduct() {
	}

	public Acmproduct(String acmproductType, String acmedition, String acmproductIntroduction, String acmproductName,
			String acmproductrUrl, String acmissn, String acmeissn, String acmproductPicUrl, byte[] acmproductPic,
			String acmproductPicName, String acmproductDescription, Date createtime, Date updatetime,
			Set<AcmproductsEditor> acmproductsEditors) {
		this.acmproductType = acmproductType;
		this.acmedition = acmedition;
		this.acmproductIntroduction = acmproductIntroduction;
		this.acmproductName = acmproductName;
		this.acmproductrUrl = acmproductrUrl;
		this.acmissn = acmissn;
		this.acmeissn = acmeissn;
		this.acmproductPicUrl = acmproductPicUrl;
		this.acmproductPic = acmproductPic;
		this.acmproductPicName = acmproductPicName;
		this.acmproductDescription = acmproductDescription;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.acmproductsEditors = acmproductsEditors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ACMProductType", length = 50)
	public String getAcmproductType() {
		return this.acmproductType;
	}

	public void setAcmproductType(String acmproductType) {
		this.acmproductType = acmproductType;
	}

	@Column(name = "ACMEdition", length = 500)
	public String getAcmedition() {
		return this.acmedition;
	}

	public void setAcmedition(String acmedition) {
		this.acmedition = acmedition;
	}

	@Column(name = "ACMProductIntroduction", length = 500)
	public String getAcmproductIntroduction() {
		return this.acmproductIntroduction;
	}

	public void setAcmproductIntroduction(String acmproductIntroduction) {
		this.acmproductIntroduction = acmproductIntroduction;
	}

	@Column(name = "ACMProductName", length = 500)
	public String getAcmproductName() {
		return this.acmproductName;
	}

	public void setAcmproductName(String acmproductName) {
		this.acmproductName = acmproductName;
	}

	@Column(name = "ACMProductrURL", length = 500)
	public String getAcmproductrUrl() {
		return this.acmproductrUrl;
	}

	public void setAcmproductrUrl(String acmproductrUrl) {
		this.acmproductrUrl = acmproductrUrl;
	}

	@Column(name = "ACMISSN")
	public String getAcmissn() {
		return this.acmissn;
	}

	public void setAcmissn(String acmissn) {
		this.acmissn = acmissn;
	}

	@Column(name = "ACMEISSN")
	public String getAcmeissn() {
		return this.acmeissn;
	}

	public void setAcmeissn(String acmeissn) {
		this.acmeissn = acmeissn;
	}

	@Column(name = "ACMProductPicUrl", length = 500)
	public String getAcmproductPicUrl() {
		return this.acmproductPicUrl;
	}

	public void setAcmproductPicUrl(String acmproductPicUrl) {
		this.acmproductPicUrl = acmproductPicUrl;
	}

	@Column(name = "ACMProductPic")
	public byte[] getAcmproductPic() {
		return this.acmproductPic;
	}

	public void setAcmproductPic(byte[] acmproductPic) {
		this.acmproductPic = acmproductPic;
	}

	@Column(name = "ACMProductPicName")
	public String getAcmproductPicName() {
		return this.acmproductPicName;
	}

	public void setAcmproductPicName(String acmproductPicName) {
		this.acmproductPicName = acmproductPicName;
	}

	@Column(name = "ACMProductDescription")
	public String getAcmproductDescription() {
		return this.acmproductDescription;
	}

	public void setAcmproductDescription(String acmproductDescription) {
		this.acmproductDescription = acmproductDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acmproduct")
	public Set<AcmproductsEditor> getAcmproductsEditors() {
		return this.acmproductsEditors;
	}

	public void setAcmproductsEditors(Set<AcmproductsEditor> acmproductsEditors) {
		this.acmproductsEditors = acmproductsEditors;
	}

}
