package com.las.WebData.entity;
// Generated 2017-9-29 16:46:02 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcmproductsEditor generated by hbm2java
 */
@Entity
@Table(name = "ACMProductsEditor", catalog = "WebData")
public class AcmproductsEditor implements java.io.Serializable {

	private Integer id;
	private Acmproduct acmproduct;
	private String acmeditorRole;
	private String acmeditorName;
	private String acmeditorFullAdress;
	private String acmeditorNation;
	private String acmeditorInstitute;
	private Integer acmeditorSequence;
	private String acmeditorPersonalUrl;
	private String acmeditorPersonalDescription;
	private byte[] acmeditorPic;
	private String acmeditorPicFileName;
	private Date createtime;
	private Date updatetime;

	public AcmproductsEditor() {
	}

	public AcmproductsEditor(Acmproduct acmproduct, String acmeditorRole, String acmeditorName,
			String acmeditorFullAdress, String acmeditorNation, String acmeditorInstitute, Integer acmeditorSequence,
			String acmeditorPersonalUrl, String acmeditorPersonalDescription, byte[] acmeditorPic,
			String acmeditorPicFileName, Date createtime, Date updatetime) {
		this.acmproduct = acmproduct;
		this.acmeditorRole = acmeditorRole;
		this.acmeditorName = acmeditorName;
		this.acmeditorFullAdress = acmeditorFullAdress;
		this.acmeditorNation = acmeditorNation;
		this.acmeditorInstitute = acmeditorInstitute;
		this.acmeditorSequence = acmeditorSequence;
		this.acmeditorPersonalUrl = acmeditorPersonalUrl;
		this.acmeditorPersonalDescription = acmeditorPersonalDescription;
		this.acmeditorPic = acmeditorPic;
		this.acmeditorPicFileName = acmeditorPicFileName;
		this.createtime = createtime;
		this.updatetime = updatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACMProduct")
	public Acmproduct getAcmproduct() {
		return this.acmproduct;
	}

	public void setAcmproduct(Acmproduct acmproduct) {
		this.acmproduct = acmproduct;
	}

	@Column(name = "ACMEditorRole")
	public String getAcmeditorRole() {
		return this.acmeditorRole;
	}

	public void setAcmeditorRole(String acmeditorRole) {
		this.acmeditorRole = acmeditorRole;
	}

	@Column(name = "ACMEditorName", length = 500)
	public String getAcmeditorName() {
		return this.acmeditorName;
	}

	public void setAcmeditorName(String acmeditorName) {
		this.acmeditorName = acmeditorName;
	}

	@Column(name = "ACMEditorFullAdress", length = 2000)
	public String getAcmeditorFullAdress() {
		return this.acmeditorFullAdress;
	}

	public void setAcmeditorFullAdress(String acmeditorFullAdress) {
		this.acmeditorFullAdress = acmeditorFullAdress;
	}

	@Column(name = "ACMEditorNation")
	public String getAcmeditorNation() {
		return this.acmeditorNation;
	}

	public void setAcmeditorNation(String acmeditorNation) {
		this.acmeditorNation = acmeditorNation;
	}

	@Column(name = "ACMEditorInstitute", length = 500)
	public String getAcmeditorInstitute() {
		return this.acmeditorInstitute;
	}

	public void setAcmeditorInstitute(String acmeditorInstitute) {
		this.acmeditorInstitute = acmeditorInstitute;
	}

	@Column(name = "ACMEditorSequence")
	public Integer getAcmeditorSequence() {
		return this.acmeditorSequence;
	}

	public void setAcmeditorSequence(Integer acmeditorSequence) {
		this.acmeditorSequence = acmeditorSequence;
	}

	@Column(name = "ACMEditorPersonalURL", length = 1000)
	public String getAcmeditorPersonalUrl() {
		return this.acmeditorPersonalUrl;
	}

	public void setAcmeditorPersonalUrl(String acmeditorPersonalUrl) {
		this.acmeditorPersonalUrl = acmeditorPersonalUrl;
	}

	@Column(name = "ACMEditorPersonalDescription", length = 65535)
	public String getAcmeditorPersonalDescription() {
		return this.acmeditorPersonalDescription;
	}

	public void setAcmeditorPersonalDescription(String acmeditorPersonalDescription) {
		this.acmeditorPersonalDescription = acmeditorPersonalDescription;
	}

	@Column(name = "ACMEditorPic")
	public byte[] getAcmeditorPic() {
		return this.acmeditorPic;
	}

	public void setAcmeditorPic(byte[] acmeditorPic) {
		this.acmeditorPic = acmeditorPic;
	}

	@Column(name = "ACMEditorPicFileName", length = 1000)
	public String getAcmeditorPicFileName() {
		return this.acmeditorPicFileName;
	}

	public void setAcmeditorPicFileName(String acmeditorPicFileName) {
		this.acmeditorPicFileName = acmeditorPicFileName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

}
