package com.las.WebData.entity;
// Generated 2017-9-30 14:53:59 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AiaaproductsEditor generated by hbm2java
 */
@Entity
@Table(name = "AIAAProductsEditor", catalog = "WebData")
public class AiaaproductsEditor implements java.io.Serializable {

	private Integer id;
	private Aiaaproduct aiaaproduct;
	private String aiaaeditorRole;
	private String aiaaeditorName;
	private String aiaaeditorFullAdress;
	private String aiaaeditorNation;
	private String aiaaeditorInstitute;
	private Integer aiaaeditorSequence;
	private String aiaaeditorPersonalUrl;
	private String aiaaeditorPersonalDescription;
	private byte[] aiaaeditorPic;
	private String aiaaeditorPicFileName;
	private Date createtime;
	private Date updatetime;

	public AiaaproductsEditor() {
	}

	public AiaaproductsEditor(Aiaaproduct aiaaproduct, String aiaaeditorRole, String aiaaeditorName,
			String aiaaeditorFullAdress, String aiaaeditorNation, String aiaaeditorInstitute,
			Integer aiaaeditorSequence, String aiaaeditorPersonalUrl, String aiaaeditorPersonalDescription,
			byte[] aiaaeditorPic, String aiaaeditorPicFileName, Date createtime, Date updatetime) {
		this.aiaaproduct = aiaaproduct;
		this.aiaaeditorRole = aiaaeditorRole;
		this.aiaaeditorName = aiaaeditorName;
		this.aiaaeditorFullAdress = aiaaeditorFullAdress;
		this.aiaaeditorNation = aiaaeditorNation;
		this.aiaaeditorInstitute = aiaaeditorInstitute;
		this.aiaaeditorSequence = aiaaeditorSequence;
		this.aiaaeditorPersonalUrl = aiaaeditorPersonalUrl;
		this.aiaaeditorPersonalDescription = aiaaeditorPersonalDescription;
		this.aiaaeditorPic = aiaaeditorPic;
		this.aiaaeditorPicFileName = aiaaeditorPicFileName;
		this.createtime = createtime;
		this.updatetime = updatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AIAAProduct")
	public Aiaaproduct getAiaaproduct() {
		return this.aiaaproduct;
	}

	public void setAiaaproduct(Aiaaproduct aiaaproduct) {
		this.aiaaproduct = aiaaproduct;
	}

	@Column(name = "AIAAEditorRole")
	public String getAiaaeditorRole() {
		return this.aiaaeditorRole;
	}

	public void setAiaaeditorRole(String aiaaeditorRole) {
		this.aiaaeditorRole = aiaaeditorRole;
	}

	@Column(name = "AIAAEditorName", length = 500)
	public String getAiaaeditorName() {
		return this.aiaaeditorName;
	}

	public void setAiaaeditorName(String aiaaeditorName) {
		this.aiaaeditorName = aiaaeditorName;
	}

	@Column(name = "AIAAEditorFullAdress", length = 2000)
	public String getAiaaeditorFullAdress() {
		return this.aiaaeditorFullAdress;
	}

	public void setAiaaeditorFullAdress(String aiaaeditorFullAdress) {
		this.aiaaeditorFullAdress = aiaaeditorFullAdress;
	}

	@Column(name = "AIAAEditorNation")
	public String getAiaaeditorNation() {
		return this.aiaaeditorNation;
	}

	public void setAiaaeditorNation(String aiaaeditorNation) {
		this.aiaaeditorNation = aiaaeditorNation;
	}

	@Column(name = "AIAAEditorInstitute", length = 500)
	public String getAiaaeditorInstitute() {
		return this.aiaaeditorInstitute;
	}

	public void setAiaaeditorInstitute(String aiaaeditorInstitute) {
		this.aiaaeditorInstitute = aiaaeditorInstitute;
	}

	@Column(name = "AIAAEditorSequence")
	public Integer getAiaaeditorSequence() {
		return this.aiaaeditorSequence;
	}

	public void setAiaaeditorSequence(Integer aiaaeditorSequence) {
		this.aiaaeditorSequence = aiaaeditorSequence;
	}

	@Column(name = "AIAAEditorPersonalURL", length = 1000)
	public String getAiaaeditorPersonalUrl() {
		return this.aiaaeditorPersonalUrl;
	}

	public void setAiaaeditorPersonalUrl(String aiaaeditorPersonalUrl) {
		this.aiaaeditorPersonalUrl = aiaaeditorPersonalUrl;
	}

	@Column(name = "AIAAEditorPersonalDescription", length = 65535)
	public String getAiaaeditorPersonalDescription() {
		return this.aiaaeditorPersonalDescription;
	}

	public void setAiaaeditorPersonalDescription(String aiaaeditorPersonalDescription) {
		this.aiaaeditorPersonalDescription = aiaaeditorPersonalDescription;
	}

	@Column(name = "AIAAEditorPic")
	public byte[] getAiaaeditorPic() {
		return this.aiaaeditorPic;
	}

	public void setAiaaeditorPic(byte[] aiaaeditorPic) {
		this.aiaaeditorPic = aiaaeditorPic;
	}

	@Column(name = "AIAAEditorPicFileName", length = 1000)
	public String getAiaaeditorPicFileName() {
		return this.aiaaeditorPicFileName;
	}

	public void setAiaaeditorPicFileName(String aiaaeditorPicFileName) {
		this.aiaaeditorPicFileName = aiaaeditorPicFileName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

}
