package com.las.WebData.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ElsevierproductsId generated by hbm2java
 */
@Embeddable
public class ElsevierproductsId implements java.io.Serializable {

	private Long id;
	private String productTyp;
	private String edition;
	private String firstPubli;
	private String print;
	private String issn;
	private String productNam;
	private String productrUr;
	private String productSou;
	private String journalEdi;
	private String journalEd1;
	private String journalDes;
	private String productsCo;
	private String productsC1;
	private Date createtime;
	private Date updatetime;

	public ElsevierproductsId() {
	}

	public ElsevierproductsId(Long id, String productTyp, String edition, String firstPubli, String print, String issn,
			String productNam, String productrUr, String productSou, String journalEdi, String journalEd1,
			String journalDes, String productsCo, String productsC1, Date createtime, Date updatetime) {
		this.id = id;
		this.productTyp = productTyp;
		this.edition = edition;
		this.firstPubli = firstPubli;
		this.print = print;
		this.issn = issn;
		this.productNam = productNam;
		this.productrUr = productrUr;
		this.productSou = productSou;
		this.journalEdi = journalEdi;
		this.journalEd1 = journalEd1;
		this.journalDes = journalDes;
		this.productsCo = productsCo;
		this.productsC1 = productsC1;
		this.createtime = createtime;
		this.updatetime = updatetime;
	}

	@Column(name = "ID")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ProductTyp", length = 40)
	public String getProductTyp() {
		return this.productTyp;
	}

	public void setProductTyp(String productTyp) {
		this.productTyp = productTyp;
	}

	@Column(name = "Edition")
	public String getEdition() {
		return this.edition;
	}

	public void setEdition(String edition) {
		this.edition = edition;
	}

	@Column(name = "FirstPubli")
	public String getFirstPubli() {
		return this.firstPubli;
	}

	public void setFirstPubli(String firstPubli) {
		this.firstPubli = firstPubli;
	}

	@Column(name = "Print")
	public String getPrint() {
		return this.print;
	}

	public void setPrint(String print) {
		this.print = print;
	}

	@Column(name = "ISSN")
	public String getIssn() {
		return this.issn;
	}

	public void setIssn(String issn) {
		this.issn = issn;
	}

	@Column(name = "ProductNam")
	public String getProductNam() {
		return this.productNam;
	}

	public void setProductNam(String productNam) {
		this.productNam = productNam;
	}

	@Column(name = "ProductrUR")
	public String getProductrUr() {
		return this.productrUr;
	}

	public void setProductrUr(String productrUr) {
		this.productrUr = productrUr;
	}

	@Column(name = "ProductSou")
	public String getProductSou() {
		return this.productSou;
	}

	public void setProductSou(String productSou) {
		this.productSou = productSou;
	}

	@Column(name = "JournalEdi")
	public String getJournalEdi() {
		return this.journalEdi;
	}

	public void setJournalEdi(String journalEdi) {
		this.journalEdi = journalEdi;
	}

	@Column(name = "JournalEd1")
	public String getJournalEd1() {
		return this.journalEd1;
	}

	public void setJournalEd1(String journalEd1) {
		this.journalEd1 = journalEd1;
	}

	@Column(name = "JournalDes")
	public String getJournalDes() {
		return this.journalDes;
	}

	public void setJournalDes(String journalDes) {
		this.journalDes = journalDes;
	}

	@Column(name = "ProductsCo")
	public String getProductsCo() {
		return this.productsCo;
	}

	public void setProductsCo(String productsCo) {
		this.productsCo = productsCo;
	}

	@Column(name = "ProductsC1")
	public String getProductsC1() {
		return this.productsC1;
	}

	public void setProductsC1(String productsC1) {
		this.productsC1 = productsC1;
	}

	@Column(name = "Createtime", length = 10)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "Updatetime", length = 10)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElsevierproductsId))
			return false;
		ElsevierproductsId castOther = (ElsevierproductsId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getProductTyp() == castOther.getProductTyp()) || (this.getProductTyp() != null
						&& castOther.getProductTyp() != null && this.getProductTyp().equals(castOther.getProductTyp())))
				&& ((this.getEdition() == castOther.getEdition()) || (this.getEdition() != null
						&& castOther.getEdition() != null && this.getEdition().equals(castOther.getEdition())))
				&& ((this.getFirstPubli() == castOther.getFirstPubli()) || (this.getFirstPubli() != null
						&& castOther.getFirstPubli() != null && this.getFirstPubli().equals(castOther.getFirstPubli())))
				&& ((this.getPrint() == castOther.getPrint()) || (this.getPrint() != null
						&& castOther.getPrint() != null && this.getPrint().equals(castOther.getPrint())))
				&& ((this.getIssn() == castOther.getIssn()) || (this.getIssn() != null && castOther.getIssn() != null
						&& this.getIssn().equals(castOther.getIssn())))
				&& ((this.getProductNam() == castOther.getProductNam()) || (this.getProductNam() != null
						&& castOther.getProductNam() != null && this.getProductNam().equals(castOther.getProductNam())))
				&& ((this.getProductrUr() == castOther.getProductrUr()) || (this.getProductrUr() != null
						&& castOther.getProductrUr() != null && this.getProductrUr().equals(castOther.getProductrUr())))
				&& ((this.getProductSou() == castOther.getProductSou()) || (this.getProductSou() != null
						&& castOther.getProductSou() != null && this.getProductSou().equals(castOther.getProductSou())))
				&& ((this.getJournalEdi() == castOther.getJournalEdi()) || (this.getJournalEdi() != null
						&& castOther.getJournalEdi() != null && this.getJournalEdi().equals(castOther.getJournalEdi())))
				&& ((this.getJournalEd1() == castOther.getJournalEd1()) || (this.getJournalEd1() != null
						&& castOther.getJournalEd1() != null && this.getJournalEd1().equals(castOther.getJournalEd1())))
				&& ((this.getJournalDes() == castOther.getJournalDes()) || (this.getJournalDes() != null
						&& castOther.getJournalDes() != null && this.getJournalDes().equals(castOther.getJournalDes())))
				&& ((this.getProductsCo() == castOther.getProductsCo()) || (this.getProductsCo() != null
						&& castOther.getProductsCo() != null && this.getProductsCo().equals(castOther.getProductsCo())))
				&& ((this.getProductsC1() == castOther.getProductsC1()) || (this.getProductsC1() != null
						&& castOther.getProductsC1() != null && this.getProductsC1().equals(castOther.getProductsC1())))
				&& ((this.getCreatetime() == castOther.getCreatetime()) || (this.getCreatetime() != null
						&& castOther.getCreatetime() != null && this.getCreatetime().equals(castOther.getCreatetime())))
				&& ((this.getUpdatetime() == castOther.getUpdatetime())
						|| (this.getUpdatetime() != null && castOther.getUpdatetime() != null
								&& this.getUpdatetime().equals(castOther.getUpdatetime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getProductTyp() == null ? 0 : this.getProductTyp().hashCode());
		result = 37 * result + (getEdition() == null ? 0 : this.getEdition().hashCode());
		result = 37 * result + (getFirstPubli() == null ? 0 : this.getFirstPubli().hashCode());
		result = 37 * result + (getPrint() == null ? 0 : this.getPrint().hashCode());
		result = 37 * result + (getIssn() == null ? 0 : this.getIssn().hashCode());
		result = 37 * result + (getProductNam() == null ? 0 : this.getProductNam().hashCode());
		result = 37 * result + (getProductrUr() == null ? 0 : this.getProductrUr().hashCode());
		result = 37 * result + (getProductSou() == null ? 0 : this.getProductSou().hashCode());
		result = 37 * result + (getJournalEdi() == null ? 0 : this.getJournalEdi().hashCode());
		result = 37 * result + (getJournalEd1() == null ? 0 : this.getJournalEd1().hashCode());
		result = 37 * result + (getJournalDes() == null ? 0 : this.getJournalDes().hashCode());
		result = 37 * result + (getProductsCo() == null ? 0 : this.getProductsCo().hashCode());
		result = 37 * result + (getProductsC1() == null ? 0 : this.getProductsC1().hashCode());
		result = 37 * result + (getCreatetime() == null ? 0 : this.getCreatetime().hashCode());
		result = 37 * result + (getUpdatetime() == null ? 0 : this.getUpdatetime().hashCode());
		return result;
	}

}
