package com.las.WebData.entity;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Elsevierproducts generated by hbm2java
 */
@Entity
@Table(name = "elsevierproducts", catalog = "market")
public class Elsevierproducts implements java.io.Serializable {

	private ElsevierproductsId id;

	public Elsevierproducts() {
	}

	public Elsevierproducts(ElsevierproductsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID")),
			@AttributeOverride(name = "productTyp", column = @Column(name = "ProductTyp", length = 40)),
			@AttributeOverride(name = "edition", column = @Column(name = "Edition")),
			@AttributeOverride(name = "firstPubli", column = @Column(name = "FirstPubli")),
			@AttributeOverride(name = "print", column = @Column(name = "Print")),
			@AttributeOverride(name = "issn", column = @Column(name = "ISSN")),
			@AttributeOverride(name = "productNam", column = @Column(name = "ProductNam")),
			@AttributeOverride(name = "productrUr", column = @Column(name = "ProductrUR")),
			@AttributeOverride(name = "productSou", column = @Column(name = "ProductSou")),
			@AttributeOverride(name = "journalEdi", column = @Column(name = "JournalEdi")),
			@AttributeOverride(name = "journalEd1", column = @Column(name = "JournalEd1")),
			@AttributeOverride(name = "journalDes", column = @Column(name = "JournalDes")),
			@AttributeOverride(name = "productsCo", column = @Column(name = "ProductsCo")),
			@AttributeOverride(name = "productsC1", column = @Column(name = "ProductsC1")),
			@AttributeOverride(name = "createtime", column = @Column(name = "Createtime", length = 10)),
			@AttributeOverride(name = "updatetime", column = @Column(name = "Updatetime", length = 10)) })
	public ElsevierproductsId getId() {
		return this.id;
	}

	public void setId(ElsevierproductsId id) {
		this.id = id;
	}

}
